### ISSUE TITLE
ERROR: quorum-genesis: not found

### ISSUE THREAD

**Issue by simonmullaney** [ConsenSys/QuorumNetworkManager#95]
Getting this error after adding a second node to network.
My dependancies:

geth version
Geth
Version: 1.5.0-unstable
Git Commit: 949b5c0d7b987b1881a68c28035d978e49fbb5ce
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7
OS: linux
GOPATH=
GOROOT=/usr/local/go

Terminal output:

simon@Node4:~/workspace/QuorumNetworkManager$ node index.js 
Trying to get public ip address, please wait a few seconds...
Welcome! 

Please enter the IP address other nodes will use to connect to this node. 

Also, please enter a publicly identifyable string for this node to use.

prompt: localIpAddress:  (13.92.188.92) 
prompt: nodeName:  Node1
Please select an option:
1) Raft
2) QuorumChain
5) Kill all geth and constellation
prompt: option:  5
ERROR: geth: no process found

geth: no process found

ERROR: constellation-node: no process found

constellation-node: no process found

Please select an option:
1) Raft
2) QuorumChain
5) Kill all geth and constellation
prompt: option:  1
Please select an option below:
----- Option 1 and 2 are for the initial setup of a raft network -----
1) Start a node as the setup coordinator [Ideally there should only be one coordinator]
2) Start a node as a non-coordinator
----- Option 3 is for joining a raft network post initial setup  -----
3) Join a raft network if you were not part of the initial setup
4) TODO: Start whisper services and attach to already running node
5) killall geth constellation-node
0) Quit
prompt: option:  1
Please select an option below:
1) Allow anyone to connect
2) [TODO] Allow only people with pre-auth tokens to connect
prompt: option:  1
Please select an option below:
1) Clear all files/configuration and start from scratch[WARNING: this clears everything]
2) Keep old files/configuration intact and start the node + whisper services
prompt: option:  1
[*] Starting new node...
Generating node key

enode: enode://edf5d03f0580a511c3425d525d6b00e330e0aebe412ad644581386fa7e8589f921037b81d5bf131615bd13d825e09f352f3d589aec43eccfb9cd0dbccec774d9@13.92.188.92:20000?raftport=40000

[*] Starting communication node...
[*] RPC connection established, Node started
Please wait for others to join. Hit any key + enter once done.
prompt: done:  Node2 has joined the network

[*] Creating genesis config...
ERROR: /bin/sh: 1: 
ERROR /bin/sh: 1: 
ERROR: quorum-genesis: not found
/home/simon/workspace/QuorumNetworkManager/node_modules/async/dist/async.js:903
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /home/simon/workspace/QuorumNetworkManager/node_modules/async/dist/async.js:903:32
    at /home/simon/workspace/QuorumNetworkManager/node_modules/async/dist/async.js:2491:13
    at /home/simon/workspace/QuorumNetworkManager/node_modules/async/dist/async.js:2552:17
    at Socket.<anonymous> (/home/simon/workspace/QuorumNetworkManager/util.js:220:5)
    at emitOne (events.js:120:20)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:264:12)
    at readableAddChunk (_stream_readable.js:247:13)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at Pipe.onread (net.js:587:20)

**Comment by coeniebeyers** [comment]
Hi! This means that `quorum-genesis` hasn't been installed yet. This should fix that:

```
cd ~/workspace
git clone https://github.com/davebryson/quorum-genesis.git
cd quorum-genesis/
sudo npm install -g
```

What does `which quorum-genesis` output?

**Comment by simonmullaney** [comment]
I'm getting nothing from `which quorum-genesis` - I think it could be due to the errors below

Im also getting errors when doing `sudo npm install -g`:

simon@Node4:~/workspace/quorum-genesis$ sudo npm install -g
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm WARN checkPermissions Missing write access to /usr/lib/node_modules/quorum-genesis
npm ERR! path /usr/lib/node_modules/quorum-genesis
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall access
npm ERR! enoent ENOENT: no such file or directory, access '/usr/lib/node_modules/quorum-genesis'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/simon/.npm/_logs/2017-10-23T14_10_25_296Z-debug.log

**Comment by simonmullaney** [comment]
Got it sorted - removed /usr/lib/node_modules/quorum-genesis, and then carried out the steps you listed above:

cd ~/workspace
git clone https://github.com/davebryson/quorum-genesis.git
cd quorum-genesis/
sudo npm install -g

Thanks again!

**Comment by coeniebeyers** [comment]
Okay awesome!

**Comment by jashradia** [comment]
> 
> 
> Hi! This means that `quorum-genesis` hasn't been installed yet. This should fix that:
> 
> ```
> cd ~/workspace
> git clone https://github.com/davebryson/quorum-genesis.git
> cd quorum-genesis/
> sudo npm install -g
> ```
> 
> What does `which quorum-genesis` output?

i have done the following steps and output of "which quorum-genesis" is` /usr/bin/quorum-genesis`
still i am getting the following error:  

prompt: localIpAddress:  52.187.12.137
prompt: nodeName:  node2
Please select an option:
1) Raft
2) Istanbul BFT
5) Kill all geth and constellation
prompt: option:  1
Please select an option below:
----- Option 1 and 2 are for the initial setup of a raft network -----
1) Start a node as the setup coordinator [Ideally there should only be one coordinator]
2) Start a node as a non-coordinator
----- Option 3 is for joining a raft network post initial setup  -----
3) Join a raft network if you were not part of the initial setup
4) TODO: Start whisper services and attach to already running node
5) Kill all geth constellation-node
0) Quit
prompt: option:  2
Please select an option below:
1) Clear all files/configuration and start from scratch[WARNING: this clears everything]
2) Keep old files/configuration intact and start the node + whisper services
3) [TODO] Keep enode and accounts, clear all other files/configuration
prompt: option:  1
In order to join the network, please enter the ip address of the coordinating node
prompt: ipAddress:  52.187.165.110
[*] Starting new node...
ERROR: INFO [02-27|10:31:38.718] Maximum peer count                       ETH=25 LES=0 total=25

ERROR INFO [02-27|10:31:38.718] Maximum peer count                       ETH=25 LES=0 total=25

/home/rbeicloudadmin/workspace/QuorumNetworkManager/node_modules/async/dist/async.js:903
        if (fn === null) throw new Error("Callback was already called.");
                         ^

Error: Callback was already called.
    at /home/rbeicloudadmin/workspace/QuorumNetworkManager/node_modules/async/dist/async.js:903:32
    at /home/rbeicloudadmin/workspace/QuorumNetworkManager/node_modules/async/dist/async.js:2491:13
    at /home/rbeicloudadmin/workspace/QuorumNetworkManager/node_modules/async/dist/async.js:2552:17
    at Socket.<anonymous> (/home/rbeicloudadmin/workspace/QuorumNetworkManager/util.js:158:7)
    at Socket.emit (events.js:185:15)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:257:13)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at Pipe.onread (net.js:581:20)
